apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
      - name: knote
        image: alejandromons/knote-java:latest
        env:
        - name: MONGO_URL
          value: mongodb://mongodb:27017/notes
        - name: MINIO_URL
          value: http://minio:9000
        - name: MINIO_ACCESS_KEY
          value: minioadmin
        - name: MINIO_SECRET_KEY
          value: minioadmin
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: knote
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  selector:
    app: knote 